# Generated by Django 5.1.7 on 2025-04-02 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=255)),
                ('usertype', models.CharField(max_length=20)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dentist', 'Dentist'), ('Homeopathy', 'Homeopathy'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Traumatology', 'Traumatology'), ('Radiology', 'Radiology')], default='Homeopathy', max_length=50)),
                ('highest_qualification', models.CharField(choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('MS', 'MS'), ('DM', 'DM')], max_length=50)),
                ('position', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Consultant', 'Consultant'), ('Head of Department', 'Head of Department')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('consultation_fee', models.IntegerField(blank=True, null=True)),
                ('emergency_fee', models.IntegerField(blank=True, null=True)),
                ('surgery_fee', models.IntegerField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField()),
                ('languages', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Chinese', 'Chinese'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic'), ('Russian', 'Russian'), ('Portuguese', 'Portuguese'), ('Japanese', 'Japanese'), ('Other', 'Other')], max_length=100)),
                ('patients_treated', models.IntegerField()),
                ('biography', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('morning_availability', models.IntegerField(blank=True, null=True)),
                ('afternoon_availability', models.IntegerField(blank=True, null=True)),
                ('evening_availability', models.IntegerField(blank=True, null=True)),
                ('telemedicine', models.BooleanField(default=False)),
                ('emergency_service', models.BooleanField(default=False)),
                ('home_visits', models.BooleanField(default=False)),
                ('international_patients', models.BooleanField(default=False)),
                ('insurance_accepted', models.BooleanField(default=False)),
                ('research_publications', models.BooleanField(default=False)),
                ('multilingual', models.BooleanField(default=False)),
                ('weekend_availability', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
