# Generated by Django 5.1.7 on 2025-04-02 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.BooleanField(default=False)),
                ('specialization', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dentist', 'Dentist'), ('Homeopathy', 'Homeopathy'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Traumatology', 'Traumatology'), ('Radiology', 'Radiology')], default='Homeopathy', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
